name: glmnet-classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - pillow
  - sphinx-gallery
  - gfortran_linux-64